# -*- coding: utf-8 -*-
"""KDD_AAT.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pU3NE5xzli3wu2ly1xUMi4-zhVmDfhuS
"""

!pip install kagglehub

import kagglehub
from kagglehub import KaggleDatasetAdapter


file_path = "american_bankruptcy.csv"


df = kagglehub.load_dataset(
  KaggleDatasetAdapter.PANDAS,
  "utkarshx27/american-companies-bankruptcy-prediction-dataset",
  file_path,
)

print("First 5 records:", df.head())

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.preprocessing import StandardScaler
from sklearn.feature_selection import VarianceThreshold
from sklearn.model_selection import train_test_split

threshold = 0.4
df=  df.loc[:, df.isna().mean()< threshold]
df = df.fillna(df.median(numeric_only=True))

df = df.drop_duplicates()

label = df['status_label']
df_features = df.drop(columns=['status_label', 'company_name', 'year'])


original_feature_columns = df_features.columns

scaler = StandardScaler()
df_features = scaler.fit_transform(df_features)
vt = VarianceThreshold(threshold=0.01)
x_var = vt.fit_transform(df_features)


selected_col = original_feature_columns[vt.get_support()]
print("Remaining columns after variance filter:", list(selected_col))

corr = pd.DataFrame(x_var, columns=selected_col).corr().abs()
upper = corr.where(np.triu(np.ones(corr.shape), k=1).astype(bool))

to_drop = [column for column in upper.columns if any(upper[column] > 0.85)]
print("Dropped due to high correlation:", to_drop)

df_filtered_features = pd.DataFrame(x_var, columns=selected_col)


X_reduced = df_filtered_features.drop(columns=to_drop).values

import matplotlib.pyplot as plt
from sklearn.cluster import KMeans

inertia_values = []
K = range(1, 11)

for k in K:
    kmeans = KMeans(n_clusters=k, random_state=42)
    kmeans.fit(X_reduced)
    inertia_values.append(kmeans.inertia_)

plt.figure(figsize=(8,5))
plt.plot(K, inertia_values, marker='o')
plt.xlabel("Number of Clusters (k)")
plt.ylabel("Inertia / Within-Cluster SSE")
plt.title("Elbow Method for Optimal k")
plt.grid(True)
plt.show()

"""Insight: The inertia (within-cluster SSE) decreases sharply from k = 1 to k ≈ 3–4, after which the rate of improvement slows significantly. This indicates that most of the meaningful structure in the data is captured by around 3 to 4 clusters, beyond which additional clusters yield diminishing returns."""

from sklearn.cluster import KMeans

kmeans = KMeans(n_clusters=3, random_state=42, n_init='auto')
clusters = kmeans.fit_predict(X_reduced)

df['clusters'] = clusters

centroids = kmeans.cluster_centers_

remaining_columns = [col for col in selected_col if col not in to_drop]
centroid_df = pd.DataFrame(centroids, columns=remaining_columns)
print(centroid_df)


cluster_names = {
    0: "High-Risk Distressed Firms",
    1: "Moderately Stable Firms",
    2: "Strong Financial Health"
}

df['cluster_name'] = df['clusters'].map(cluster_names)

pd.crosstab(df['cluster_name'], df['status_label'])

from sklearn.decomposition import PCA
import matplotlib.pyplot as plt

pca = PCA(n_components=2)
components = pca.fit_transform(X_reduced)

plt.figure(figsize=(8,6))
plt.scatter(components[:,0], components[:,1], c=df['clusters'], cmap='viridis')
plt.title("Clusters of Companies Based on Financial Metrics")
plt.xlabel("PC1")
plt.ylabel("PC2")
plt.show()

"""Insight: The clustering reveals three well-defined segments of companies with progressively increasing PC1 values. The leftmost cluster is compact and homogeneous, indicating firms with similar financial structures, while the rightmost cluster is more dispersed, suggesting greater variability among larger or more extreme financial profiles."""

cluster_profile = df.groupby('cluster_name')[remaining_columns].mean()
print(cluster_profile)