# -*- coding: utf-8 -*-
"""Analysing Survival on the Titanic.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GbBIS-pIdoZmSf9f7d6HyJL3kMlNUMuy
"""

!git clone http://github.com/HarshvardhanSingh-13/Datasets

!pip install ydata-profiling -q

df.to_html('Analysis_1.html')

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

df = pd.read_csv('/content/Datasets/Titanic_Dataset/Titanic-Dataset.csv')

df.head()

df.info()

df.isna().sum()

"""Insight: Columns such as Age, Cabin and Enbarked have missing values. Would be useful to impute the missing data.

"""

median_age = df['Age'].median()
print(median_age)
df['Age'] = df['Age'].fillna(median_age)
df.isna().sum()

"""The Age coloumn has been filled with the median age of the passengers(which turns out to be 28.0) on board Titanic. Median is chosen as it is unaffected by outliers, unlike mean."""

mode_embarked = df['Embarked'].mode()[0]
print(mode_embarked)
df['Embarked'] = df['Embarked'].fillna(mode_embarked)
df.isna().sum()

"""The 'Embarked' column has been filled with the mode(Highest count in Embarked Coloumn), which was S. The mode is chosen because the number of passengers from S is high and adding two more rows to S would have a negligible change to the distribution of Embarked"""

print(df.columns)

df['Has_Cabin'] = df['Cabin'].notna().astype(int)
df.drop('Cabin',axis = 1, inplace=True)
df.head()

df.isna().sum()

from ydata_profiling import ProfileReport
profile = ProfileReport(df, title = "Titanic Dataset Profile Report")
profile.to_notebook_iframe()

profile.to_file("Analysis.html")