# -*- coding: utf-8 -*-
"""Credit Risk & Default Analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CyZFV9Pi6QgLBwSRFJFhi9bCQ2ANc0Zj
"""

!pip install kagglehub

import kagglehub
from kagglehub import KaggleDatasetAdapter

file_path = "lending_club_loan_two.csv"

df = kagglehub.load_dataset(KaggleDatasetAdapter.PANDAS,"gabrielsantello/lending-club-loan-preprocessed-dataset",file_path,)

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

missing_values = pd.DataFrame({'Count':df.isna().sum(),'Percentage':(df.isna().sum()/len(df))*100})
print(missing_values)

"""Since percentage of misssing values is negligible (emp_title ~5.7%, emp_length ~4.6%, title ~0.4%, revol_util ~0.06%, mort_acc ~9.34% and pub_rec_bankruptcies ~0.13%), we drop those rows from our dataset."""

df = df.dropna()

missing_values = pd.DataFrame({'Count':df.isna().sum(),'Percentage':(df.isna().sum()/len(df))*100})
print(missing_values)

"""Now we have a perfectly clean dataset to work with, let's explore our dataset to understand it better."""

df.info()

df.head()

df['term'] = df['term'].apply(lambda x: int(x.split()[0]))

"""We converted term feature's object datatype to a interger by extracting only the numerical part of it."""

df_copy = df.copy()

emp_map = {
    '< 1 year': 0, '1 year': 1, '2 years': 2, '3 years': 3, '4 years': 4,
    '5 years': 5, '6 years': 6, '7 years': 7, '8 years': 8, '9 years': 9, '10+ years': 10
}

df['emp_length'] = df['emp_length'].map(emp_map)
df['emp_length'] = df['emp_length'].fillna(0)


grade_map = {'A': 1, 'B': 2, 'C': 3, 'D': 4, 'E': 5, 'F': 6, 'G': 7}
df['grade'] = df['grade'].map(grade_map)

sub_grades = sorted(df['sub_grade'].unique())
sub_grade_map = {val: i+1 for i, val in enumerate(sub_grades)}
df['sub_grade'] = df['sub_grade'].map(sub_grade_map)

"""We map employment length to our given mapping, getting rid of it's object datatype, making it a cardinal number."""

df = df.drop(['address', 'issue_d', 'emp_title', 'title'], axis=1)

"""Drop these variables, as they have too many unique values to be useful for EDA

"""

df['loan_repaid'] = df['loan_status'].map({'Fully Paid': 1, 'Charged Off': 0})
df = df.drop('loan_status', axis=1)

df_copy['loan_repaid'] = df_copy['loan_status'].map({'Fully Paid': 1, 'Charged Off': 0})
df_copy = df_copy.drop('loan_status', axis=1)

print(df.select_dtypes(include=['object']).columns)

df['earliest_cr_line'] = pd.to_datetime(df['earliest_cr_line'])
df['earliest_cr_line'] = 2026 - df['earliest_cr_line'].dt.year

cat_cols = ['home_ownership', 'verification_status', 'purpose',
            'initial_list_status', 'application_type']

df_final = pd.get_dummies(df, columns=cat_cols, drop_first=True)

"""We will make loan repaid a binary value, making it easy for EDA

EDA

1. Which borrower characteristics most strongly predict default?
"""

from sklearn.ensemble import RandomForestClassifier

X = df_final.drop('loan_repaid', axis=1)
y = df_final['loan_repaid']


model = RandomForestClassifier(n_jobs=-1, n_estimators=100, random_state=42)
model.fit(X, y)


importances = pd.Series(model.feature_importances_, index=X.columns)
print("--- TOP 10 PREDICTORS OF DEFAULT ---")
print(importances.sort_values(ascending=False).head(10))

"""Insight: Default risk is most strongly associated with indicators of financial strain and credit utilization. Borrowers with higher debt-to-income ratios, larger revolving balances, and high credit utilization are significantly more likely to default, while income and loan pricing factors also play an important role.

2. Which loan segments generate the highest losses?
"""

df.head()

loss_by_grade = (df_copy[df_copy['loan_repaid'] == 0].groupby('grade')['loan_amnt'].sum().sort_values(ascending=False))
loss_by_grade.plot(kind='bar')
plt.title("Total Loss by Loan Grade")
plt.ylabel("Total Defaulted Amount")
plt.show()

"""Insight: Mid-tier credit grades, particularly Grade C and D, generate the highest total losses. These segments combine substantial loan volume with elevated default risk, resulting in the largest aggregate financial impact.

3. How does default risk change across loan term and Grade?
"""

term_grade_risk = df_copy.groupby(['grade', 'term'])['loan_repaid'].mean().unstack()
term_grade_default = (1-term_grade_risk)*100

term_grade_default.plot(kind='bar', figsize=(12,6), width=0.8)
plt.title('Default Risk: Grade vs. Duration', fontsize=14)
plt.ylabel('Default Rate (%)')
plt.legend(title='Term (Months)')
plt.show()

"""Insight: Default risk increases steadily as credit grade deteriorates, and for every grade, 60-month loans exhibit higher default rates than 36-month loans. This indicates that both borrower credit quality and loan duration independently amplify repayment risk.

4. Are high-interest loans compensating for higher risk or just masking it?
"""

avg_int_rate = df_copy.groupby(['grade', 'term'])['int_rate'].mean().unstack()
net_spread = avg_int_rate - term_grade_default

plt.figure(figsize=(10,6))
sns.heatmap(net_spread, annot=True, cmap='RdYlGn', fmt='.2f')
plt.title('Net Profitability Map: Interest Rate minus Default Risk', fontsize=14)
plt.ylabel('Loan Grade')
plt.xlabel('Loan Term (Months)')
plt.show()

"""Insight: Profitability declines sharply as credit quality worsens and loan duration increases. Only top-grade borrowers (Grade A) on shorter terms generate positive net returns, while most lower-grade and longer-term loans appear unprofitable after accounting for default risk.

5. What borrower profile represents the safest lending opportunity?
"""

df_copy['income_bins'] = pd.qcut(df_copy['annual_inc'], q=5, labels=['Very Low', 'Low', 'Medium', 'High', 'Very High'])


safe_matrix = df_copy.pivot_table(index='income_bins', columns='home_ownership', values='loan_repaid', aggfunc=lambda x: (x == 0).mean() * 100)


safe_matrix = safe_matrix[['MORTGAGE', 'OWN', 'RENT']]

plt.figure(figsize=(10,6))
sns.heatmap(safe_matrix, annot=True, cmap='RdYlGn_r', fmt='.1f')
plt.title("Default Probability by Income and Home Status (%)")
plt.show()

"""Default risk decreases as income lowers and is consistently highest among renters. Borrowers with very low income who rent exhibit the greatest default probability, while high-income homeowners with mortgages show the lowest risk."""